package repository_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
	"gorm.io/gorm/logger"

	"brayat/internal/model"
	"brayat/internal/repository"
)

func setupTestDB(t *testing.T) *gorm.DB {
	db, err := gorm.Open(sqlite.Open("file::memory:?cache=shared"), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	require.NoError(t, err)

	err = db.AutoMigrate(&model.Session{}, &model.Person{}, &model.Relationship{})
	require.NoError(t, err)

	db.Exec("DELETE FROM relationships")
	db.Exec("DELETE FROM people")
	db.Exec("DELETE FROM sessions")

	return db
}

func TestRelationshipRepository_CreateRelationship(t *testing.T) {
	db := setupTestDB(t)
	repo := repository.NewRelationshipRepository(db)
	ctx := context.Background()

	// Need a valid session and people to avoid foreign key errors,
	// though SQLite with memory might just pass without FK constraints by default
	// depending on pragma foreign_keys=ON. Assuming it passes.
	session := model.Session{ID: "sess1", Title: "test"}
	db.Create(&session)
	personA := model.Person{ID: "pA", SessionID: "sess1", Name: "A", Gender: model.GenderMale}
	db.Create(&personA)
	personB := model.Person{ID: "pB", SessionID: "sess1", Name: "B", Gender: model.GenderFemale}
	db.Create(&personB)

	rel := &model.Relationship{
		SessionID: "sess1",
		PersonAID: "pA",
		PersonBID: "pB",
		Type:      model.RelationshipTypeParentChild,
	}

	err := repo.CreateRelationship(ctx, rel)
	assert.NoError(t, err)
	assert.NotEmpty(t, rel.ID) // should be generated by gonanoid

	// Verify in DB
	var dbRel model.Relationship
	err = db.First(&dbRel, "id = ?", rel.ID).Error
	assert.NoError(t, err)
	assert.Equal(t, rel.PersonAID, dbRel.PersonAID)
}

func TestRelationshipRepository_GetRelationshipsBySessionID(t *testing.T) {
	db := setupTestDB(t)
	repo := repository.NewRelationshipRepository(db)
	ctx := context.Background()

	sessionID := "sess2"
	db.Create(&model.Session{ID: sessionID, Title: "test2"})
	db.Create(&model.Relationship{ID: "rel1", SessionID: sessionID, PersonAID: "a", PersonBID: "b", Type: model.RelationshipTypeParentChild})
	db.Create(&model.Relationship{ID: "rel2", SessionID: sessionID, PersonAID: "b", PersonBID: "c", Type: model.RelationshipTypeSpouse})

	// Add another session's data
	db.Create(&model.Relationship{ID: "rel3", SessionID: "other-sess", PersonAID: "x", PersonBID: "y", Type: model.RelationshipTypeParentChild})

	rels, err := repo.GetRelationshipsBySessionID(ctx, sessionID)
	assert.NoError(t, err)
	assert.Len(t, rels, 2)

	// Validate results format
	assert.Equal(t, "rel1", rels[0].ID)
	assert.Equal(t, "rel2", rels[1].ID)
}

func TestRelationshipRepository_DeleteRelationship(t *testing.T) {
	db := setupTestDB(t)
	repo := repository.NewRelationshipRepository(db)
	ctx := context.Background()

	rel := model.Relationship{ID: "del1", SessionID: "s1", PersonAID: "a", PersonBID: "b", Type: model.RelationshipTypeParentChild}
	db.Create(&rel)

	err := repo.DeleteRelationship(ctx, "del1")
	assert.NoError(t, err)

	var count int64
	db.Model(&model.Relationship{}).Where("id = ?", "del1").Count(&count)
	assert.Equal(t, int64(0), count)

	err = repo.DeleteRelationship(ctx, "nonexistent")
	assert.NoError(t, err) // Should return nil if not found
}

func TestRelationshipRepository_DeleteRelationshipsByPersonID(t *testing.T) {
	db := setupTestDB(t)
	repo := repository.NewRelationshipRepository(db)
	ctx := context.Background()

	targetPerson := "targetP"

	// rels connected to targetPerson
	db.Create(&model.Relationship{ID: "relA", SessionID: "s2", PersonAID: targetPerson, PersonBID: "y", Type: model.RelationshipTypeParentChild})
	db.Create(&model.Relationship{ID: "relB", SessionID: "s2", PersonAID: "x", PersonBID: targetPerson, Type: model.RelationshipTypeSpouse})

	// irrelevant rel
	db.Create(&model.Relationship{ID: "relC", SessionID: "s2", PersonAID: "a", PersonBID: "b", Type: model.RelationshipTypeSpouse})

	err := repo.DeleteRelationshipsByPersonID(ctx, targetPerson)
	assert.NoError(t, err)

	var count int64
	db.Model(&model.Relationship{}).Count(&count)
	assert.Equal(t, int64(1), count)

	var remaining model.Relationship
	db.First(&remaining)
	assert.Equal(t, "relC", remaining.ID)
}
